### ISSUE TITLE
net.alenzen.a2l.antlr.a2lLexer package is missing

### ISSUE THREAD

**Issue by YashzAlphaGeek** [Luncher91/A2LParser#18]
Once after downloading the source code, I have seen the missing package.

Could you please help me out with how to resolve the imports?

**Comment by Luncher91** [comment]
HI, sure. It looks like that the a2lLexer has not been generated by the ANTLR4 plugin which is referenced in the pom.xml
Are you using maven to build the project?

**Comment by mirzachi** [comment]
Hi, I am facing the same problem with maven. The antlr Java classes are missing, i.e., are not generated. Do you have any suggestion on how to fix this?

**Comment by Luncher91** [comment]
Please feel free to reopen the issue if you have anymore questions.
