### ISSUE TITLE
A problem when parse Description in 'CHARACTERISTIC'

### ISSUE THREAD

**Issue by kdsam2789** [Luncher91/A2LParser#28]
Hi,

First of all, thank you for developing a good parser.

I need to parse an A2L file, a slight problem when parsing "CHARACTERISTIC".

While parsing a few A2L files, I found a case where "\e" was included in the description as shown below.

`/begin CHARACTERISTIC ASAM_CURVE_STD_AXIS "Curve with \end standard axis" CURVE ...`

ANTLR failed to parse because "\e" is a special character that is not commonly used...

It may be a normal situation to not be able to parse, but I think it is also good to parse A2L even in this case.

When analyzing Description, is it possible to set all the characters between " and " to String object?

**Comment by Luncher91** [comment]
Hi,

Thank you for bringing that up. I commited some changes which should improve the string literal handling a lot including  support for multi line handling.

I would love to get your feedback on the change before I put out a new release.

**Comment by kdsam2789** [comment]
Thank you for your quick feedback.

When I checked with the new release version, I checked that description with '\e' can be analyzed.

I analyzed all the A2L files that I have, I also inform you that most of them have been successful.

Additionally, I have a question during the analysis.

If the description contains two consecutive ", i checked the string object and found only one " left.

A2L file : 
`/begin CHARACTERISTIC ASAM_CURVE_STD_AXIS "Curve with ""end standard axis" CURVE ...`

Asap2File > Project > Module > Characteristic > String longIdentifier : 
`Curve with "end standard axis`

I wonder if you intended this result.

There's no problem with the big flow, I think it's better to keep the description strings.

**Comment by Luncher91** [comment]
Sounds great. I really appreciate your help, thank you 👍 

When you write "most of them" I wonder why some of them failed.

Regarding the double quotes: The ASAM standard supports doubled double-quotes as a way to escape a double-quote for compatibility reasons. So doubled double-quotes are equivalent to `\"` 

I totally agree with your statement to keep the string as unmodified as possible but I think it is more important to be as close to the standard as possible.

**Comment by Luncher91** [comment]
I will close the issue for now since it seems to be fixed
