### ISSUE TITLE
NPE when line breaks present in  strings after updating to 2.5.4

### ISSUE THREAD

**Issue by chintaka** [Luncher91/A2LParser#35]
Steps to reproduce : 

 In  **freeTest.a2l**   Change  **/begin MEASUREMENT superMeasurement "ultimate test"**   to 
**/begin MEASUREMENT superMeasurement "ultimate 
test"**

NPE thrown at String stringVal = stringToken.getText(); inside private String extractString(Token stringToken)  in A2LVisitor  class 

Thanks in advance.

**Comment by Luncher91** [comment]
You have mentioned that you updated to 2.5.4 when the NPE has been thrown. Did it work before and if so which version was it?

In general describes the Asam standard multi line strings being ANSI C compliant which means that a line break would need to be escaped by a backslash. So the example you have made is actually not compliant with the standard. Nevertheless it should not throw an NPE but give helpful parsing errors instead.

For that matter I am interested in your experiences with other tools. Do they accept line breaks within strings without escaping them?

**Comment by chintaka** [comment]
I upgraded from 2.4.2. When I downgraded version back 2.4.2 I' don't get the NPE.
I agree that these string are not not compliant , but some tool are less strict when comes to ASAM standard. 
I was able to get around the NPE r by  adding 

```
private String extractString(Token stringToken) {
		if(stringToken == null){
			return null;
		`}`
```

And still reports errors properly. 
For example in freeTest.a2l , when I change 

```
/begin MEASUREMENT superMeasurement "ultimate
		test"
			UBYTE THE.IDENTITY 1 2.1 4.2 255 
```

Line 229@38: token recognition error at: '"ultimate\n'

**Comment by Luncher91** [comment]
Perfect :-) I actually prepared exactly that change and pushed it now. Thank you again for pointing this issue out - I am still thinking about what the best way to go is - if I should stick to the standard or if I should be less strict about the specification and support everything which is out their.

**Comment by chintaka** [comment]
Awesome , I  will update to your latest version. Thanks for the quick response!
