### ISSUE TITLE
Can Parser Elf File

### ISSUE THREAD

**Issue by 321Oscar** [Luncher91/A2LParser#42]
i want to get Variable and address,type from elf,and add to a2l file.

**Comment by 321Oscar** [comment]
this is a ELFParser,but not support DWARF4:https://github.com/csholmq/ElfParser

**Comment by Luncher91** [comment]
If you need DWARF4 support for the ELF Parser I would guess that you create an issue over there instead.

What exactly is your concern with my A2LParser?

**Comment by 321Oscar** [comment]
i want to Modify Measurement 's address from ELF File
