### ISSUE TITLE
Support input file modification encoding

### ISSUE THREAD

**Issue by 321Oscar** [Luncher91/A2LParser#45]
Hello,
I use the jar package to parse the a2l file and input the utf8 format a2l file with Chinese characters,but Chinese cannot be recognized.
and use jar output a2l file，it is utf-8-bom.
So i want use jar to parse utf-8-without bom a2l file

**Comment by Luncher91** [comment]
Hi, 

thanks for bringing that up. The standard defines the ISO_8859_1 Charset as default. That is the reason why it is used in case there is no BOM present.

Especially with regard to other tools I would recommend to use BOM to make sure the encoding is right everywhere.

Nevertheless I would love to support different default encodings especially through the CLI. Feel free to create a Pull Request if you can add support for that.

I will keep this one on my list of wanted features for my next coding session 😉

Kind regards,
Andreas

**Comment by Luncher91** [comment]
Please have a look on the most recent version
[v2.7.0](https://github.com/Luncher91/A2LParser/releases/tag/v2.7.0)

I have added a new parameter "inputEncoding"

Please give me some feedback if that works in your case.

**Comment by 321Oscar** [comment]
Hi

I use 2.7.0  with cmd : java  -jar .\a2lparser.jar -mj -ic UTF-8 -a2l ".\xcp\test.a2l" and report error

Exception in thread "main" java.lang.IllegalArgumentException: Null charset name
        at java.base/java.nio.charset.Charset.lookup(Charset.java:455)
        at java.base/java.nio.charset.Charset.forName(Charset.java:526)
        at net.alenzen.a2l.Asap2Parser.setDefaultEncoding(Asap2Parser.java:376)
        at net.alenzen.a2l.Asap2Parser.main(Asap2Parser.java:349)

**Comment by 321Oscar** [comment]
hi, 

it works when i use cmd : java -jar .\a2lparser.jar -mj -ic UTF-8 -c UTF-8 -a2l ".\xcp\test.a2l"

bug at net.alenzen.a2l.Asap2Parser.main(Asap2Parser.java:349)
``` java
if(cmd.hasOption(inputEncodingOption.getOpt())) {
    //parser.setDefaultEncoding(cmd.getOptionValue(encodingOption.getOpt()));
    parser.setDefaultEncoding(cmd.getOptionValue(inputEncodingOption.getOpt()));
	}

```

**Comment by Luncher91** [comment]
Sorry for that - next try: [v2.7.1](https://github.com/Luncher91/A2LParser/releases/tag/v2.7.1)

**Comment by 321Oscar** [comment]
It works.
Thank you very much!
